# Generated by Django 4.1 on 2024-03-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kona_detection', '0002_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfs',
            name='pdf_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
